import { spawn } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import crypto from "node:crypto";
import { DatabaseSync } from "node:sqlite";

const root=path.resolve(new URL("..",import.meta.url).pathname),tmp=fs.mkdtempSync(path.join(os.tmpdir(),"companion-compat-test-")),dbPath=path.join(tmp,"test.db"),mockPort=21600+Math.floor(Math.random()*250),corePort=mockPort+300,key="compat-test-key-long-random-value";
const env={...process.env,MOCK_PORT:String(mockPort),COMPANION_HOST:"127.0.0.1",COMPANION_PORT:String(corePort),COMPANION_API_KEY:key,COMPANION_ADMIN_KEY:key,DATABASE_PATH:dbPath,COMPANION_MODULES_DIR:path.join(tmp,"empty-modules"),COMPANION_MODULES_STATE_PATH:path.join(tmp,"modules-state.json"),COMPANION_MODULE_EXECUTION_LEDGER_PATH:path.join(tmp,"module-execution-ledger.json"),COMPANION_MODULES_CONFIG_DIR:path.join(tmp,"modules-config"),COMPANION_MODULE_EXECUTION_LEDGER_PATH:path.join(tmp,"module-execution-ledger.json"),COMPANION_BLOCK_REAL_UPSTREAM:"1",UPSTREAM_BASE_URL:`http://127.0.0.1:${mockPort}/v1`,UPSTREAM_API_KEY:"",UPSTREAM_CHAT_MODEL:"mock-chat",UPSTREAM_AGENT_MODEL:"mock-agent",UPSTREAM_SUMMARY_MODEL:"mock-summary",UPSTREAM_SECONDARY_BASE_URL:"",UPSTREAM_SECONDARY_API_KEY:"",UPSTREAM_SECONDARY_MODEL:"",UPSTREAM_CHAT_BASE_URL:`http://127.0.0.1:${mockPort}/v1`,UPSTREAM_CHAT_API_KEY:"",UPSTREAM_AGENT_BASE_URL:`http://127.0.0.1:${mockPort}/v1`,UPSTREAM_AGENT_API_KEY:"",UPSTREAM_SUMMARY_BASE_URL:`http://127.0.0.1:${mockPort}/v1`,UPSTREAM_SUMMARY_API_KEY:"",UPSTREAM_PRIMARY_BASE_URL:"",UPSTREAM_PRIMARY_API_KEY:"",UPSTREAM_TIMEOUT_MS:"250",SUMMARY_TIMEOUT_MS:"2000",SUMMARY_EVERY_MESSAGES:"2",SUMMARY_MAX_MESSAGES:"50",SUMMARY_RETRY_COOLDOWN_SECONDS:"1",EMBEDDING_ENABLED:"false",PERSONA_SYNC_ON_START:"true",AGENT_INCLUDE_STORED_RECENT:"false",AGENT_TOOL_MODE:"compat",AGENT_TOOL_PROTOCOL_RETRIES:"1",NETWORK_CIRCUIT_OPEN_MS:"1000"};
const children=[];let core;
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),assert=(v,m)=>{if(!v)throw new Error(`ASSERT compat: ${m}`);};
function start(file,e=env){const p=spawn(process.execPath,[file],{cwd:root,env:e,stdio:["ignore","pipe","pipe"]});children.push(p);p.stdout.on("data",d=>process.stdout.write(`[child] ${d}`));p.stderr.on("data",d=>process.stderr.write(`[child-err] ${d}`));return p;}
async function wait(url){for(let i=0;i<100;i++){try{const r=await fetch(url);if(r.ok)return;}catch{}await sleep(40);}throw new Error(`timeout waiting ${url}`);}
async function stop(p){if(!p||p.exitCode!==null)return;p.kill("SIGTERM");await Promise.race([new Promise(r=>p.once("exit",r)),sleep(1000)]);}
async function request(pathname,{method="GET",body,headers={},auth=true,signal}={}){const r=await fetch(`http://127.0.0.1:${corePort}${pathname}`,{method,signal,headers:{...(auth?{authorization:`Bearer ${key}`}:{q:"1"}),...(body?{"content-type":"application/json"}:{}),...headers},body:body?JSON.stringify(body):undefined});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data=text}return {r,data,text};}
async function api(pathname,options){const x=await request(pathname,options);if(!x.r.ok)throw new Error(`${pathname} ${x.r.status}: ${x.text}`);return x.data;}
async function responses({input,stream=false,session,headers={},tools=[],toolChoice="auto"}){const hs={"x-companion-source":"opencode",...headers};if(session)hs["x-companion-session"]=session;return request("/v1/responses",{method:"POST",headers:hs,body:{model:"yuna-agent",input,stream,tools,tool_choice:toolChoice,parallel_tool_calls:false}});}
async function chat({messages,stream=false,session,model="yuna-agent",source="opencode",tools=[],toolChoice="auto"}){return request("/v1/chat/completions",{method:"POST",headers:{"x-companion-source":source,"x-companion-session":session},body:{model,messages,stream,tools,tool_choice:toolChoice}});}
const echoTool={type:"function",name:"echo_test",description:"Echo one safe value",parameters:{type:"object",properties:{value:{type:"string",enum:["ok"]}},required:["value"],additionalProperties:false}};
const loopTools=[{type:"function",name:"first_tool",description:"First",parameters:{type:"object",properties:{step:{type:"integer",enum:[1]}},required:["step"],additionalProperties:false}},{type:"function",name:"second_tool",description:"Second",parameters:{type:"object",properties:{step:{type:"integer",enum:[2]}},required:["step"],additionalProperties:false}}];
const catalogTool=(name,index)=>({type:"function",name,description:`Deterministic catalog tool ${index} ${"long capability explanation ".repeat(12)}`,parameters:{type:"object",properties:{value:{type:"string",enum:["ok"]}},required:["value"],additionalProperties:false}});
const largeTools=Array.from({length:55},(_,i)=>catalogTool(`catalog_${i}`,i));largeTools[0]=catalogTool("front_catalog_tool",0);largeTools[27]=catalogTool("middle_catalog_tool",27);largeTools[54]=catalogTool("end_catalog_tool",54);
const devTools=[{type:"function",name:"read_file",description:"Read a workspace file",parameters:{type:"object",properties:{path:{type:"string"}},required:["path"],additionalProperties:false}},{type:"function",name:"edit_file",description:"Edit a workspace file",parameters:{type:"object",properties:{path:{type:"string"},content:{type:"string"}},required:["path","content"],additionalProperties:false}},{type:"function",name:"run_test",description:"Run a safe test command",parameters:{type:"object",properties:{command:{type:"string"}},required:["command"],additionalProperties:false}}];
const actionTools=[
  {type:"function",name:"ask_user_question",description:"Ask for a user choice",parameters:{type:"object",properties:{question:{type:"string"}},required:["question"],additionalProperties:false}},
  {type:"function",name:"bash",description:"Execute a bash shell command for downloads, installs and programs",parameters:{type:"object",properties:{command:{type:"string"}},required:["command"],additionalProperties:false}},
  {type:"function",name:"edit_file",description:"Edit or patch a workspace file",parameters:{type:"object",properties:{path:{type:"string"},content:{type:"string"}},required:["path","content"],additionalProperties:false}},
  {type:"function",name:"read_file",description:"Read a workspace file",parameters:{type:"object",properties:{path:{type:"string"}},required:["path"],additionalProperties:false}},
  {type:"function",name:"glob",description:"List workspace files",parameters:{type:"object",properties:{pattern:{type:"string"}},required:["pattern"],additionalProperties:false}},
  {type:"function",name:"grep",description:"Search workspace text",parameters:{type:"object",properties:{query:{type:"string"}},required:["query"],additionalProperties:false}},
  {type:"function",name:"run_tests",description:"Run tests, checks and verification commands",parameters:{type:"object",properties:{command:{type:"string"}},required:["command"],additionalProperties:false}},
  {type:"function",name:"web_search",description:"Search the web for current sources",parameters:{type:"object",properties:{query:{type:"string"}},required:["query"],additionalProperties:false}},
  ...Array.from({length:18},(_,i)=>catalogTool(`action_optional_${i}`,100+i))
];
const callOf=x=>(x?.output??[]).find(i=>i?.type==="function_call"),textOf=x=>(x?.output??[]).filter(i=>i?.type==="message").flatMap(i=>i.content??[]).map(i=>i.text??"").join("");
function sseEvents(raw){const out=[];for(const frame of raw.split(/\r?\n\r?\n/)){const data=frame.split(/\r?\n/).filter(x=>x.startsWith("data:")).map(x=>x.slice(5).trim()).join("\n");if(!data||data==="[DONE]")continue;try{out.push(JSON.parse(data));}catch{}}return out;}
async function stats(){return (await (await fetch(`http://127.0.0.1:${mockPort}/stats`)).json());}
async function reset(){await fetch(`http://127.0.0.1:${mockPort}/reset`,{method:"POST"});}
async function waitFor(fn,label){for(let i=0;i<120;i++){const value=await fn();if(value)return value;await sleep(50);}throw new Error(`timeout: ${label}`);}

try{
  start(path.join(root,"scripts/mock-upstream.js"));await wait(`http://127.0.0.1:${mockPort}/stats`);core=start(path.join(root,"src/server.js"));await wait(`http://127.0.0.1:${corePort}/health`);
  const status=await api("/admin/status");assert(status.version==="0.2.8.0"&&status.agent_tool_mode==="compat","v0.2.8.0 compat mode active");assert(status.sqlite.user_version===6&&status.sqlite.schema_version===6,"current schema active");

  const persona={id:"yuna",name:"星铃 Yuna",version:2,core_identity:"你是星铃守护者，保持长期连续的 Yuna 身份。",personality:["机敏","温柔"],speaking_style:{tone:"熟悉而坚定",verbosity:"concise",emoji_frequency:"none",rules:["每次最终回答以「星铃｜」开头","不得泄露内部协议"]},mode_instructions:{chat:"自然聊天。",agent:"AGENT_MODE_MARKER：保持 Yuna 人格，同时准确执行工程任务。",summary:"忠于事实。"},memory:{enabled:true,chat_retrieval_limit:6,agent_retrieval_limit:3}};
  await api("/admin/personas/import",{method:"POST",body:persona});const memory=(await api("/admin/memories",{method:"POST",body:{content:"用户喜欢机械键盘",type:"preference",importance:1,status:"active",source:"manual"}})).memory;
  await responses({input:"seed",session:"compat-context"});await waitFor(async()=>(await api("/admin/status")).workers.summary_running===0,"seed summary");
  const setupDb=new DatabaseSync(dbPath),contextSession=setupDb.prepare("SELECT id FROM sessions WHERE external_key='compat-context'").get();setupDb.prepare("UPDATE sessions SET summary=? WHERE id=?").run("COMPAT_SESSION_SUMMARY",contextSession.id);setupDb.prepare("INSERT INTO events(id,persona_id,session_id,source,content,importance,created_at) VALUES(?,?,?,?,?,?,?)").run(crypto.randomUUID(),"yuna",contextSession.id,"opencode","COMPAT_SHARED_EVENT",1,new Date().toISOString());setupDb.close();
  const context=await responses({input:"我之前喜欢什么键盘？ COMPAT_CONTEXT_CHECK COMPAT_SHARED_EVENT",session:"compat-context"});assert(context.r.ok&&textOf(context.data)==="星铃｜YUNA_PERSONA_CONTEXT_OK","Persona identity, personality, style, Agent Mode, Memory, Event and Summary survive compat");const used=await api(`/admin/memories/${memory.id}`);assert(used.access_count>=1&&used.last_accessed_at,"Memory access count updates");
  const continuityFirst=(await responses({input:"我之前喜欢什么键盘？ COMPAT_SINGLE COMPAT_SHARED_EVENT",session:"compat-context",tools:[echoTool],toolChoice:"required"})).data,continuityCall=callOf(continuityFirst);await waitFor(async()=>(await api("/admin/status")).workers.summary_running===0,"context summary idle");const continuityDb=new DatabaseSync(dbPath);continuityDb.prepare("UPDATE sessions SET summary=? WHERE id=?").run("COMPAT_SESSION_SUMMARY",contextSession.id);continuityDb.close();await responses({input:[{type:"function_call_output",call_id:continuityCall.call_id,output:"continuity-result"}],session:"compat-context",tools:[],toolChoice:"none"});const continuityStats=(await stats()).lastCompat;assert(continuityStats.hasMemory&&continuityStats.hasEvent&&continuityStats.hasSummary&&continuityStats.hasPersona,"tool-output-only turn retains Persona, Memory, Event and Summary context");

  await reset();const single=await responses({input:"COMPAT_SINGLE",session:"compat-single",tools:[echoTool],toolChoice:"required"}),singleCall=callOf(single.data);assert(single.r.ok&&singleCall?.name==="echo_test"&&/^call_[0-9a-f]{32}$/.test(singleCall.call_id)&&JSON.parse(singleCall.arguments).value==="ok","single Responses native function_call, valid call_id and arguments");assert(!single.text.includes('"type":"tool_call"'),"internal decision JSON not leaked");
  const singleStats=await stats(),captured=singleStats.lastCompat;assert(singleStats.compatRequests===1&&captured.model==="mock-agent"&&captured.responseFormat?.type==="json_object"&&captured.temperature===0&&!captured.hasNativeTools,"one direct structured compat request without native fallback");assert(captured.catalog[0].name==="echo_test"&&captured.catalog[0].parameters.required[0]==="value"&&captured.catalog[0].parameters.additionalProperties===false&&captured.catalog[0].parameters.properties.value.enum[0]==="ok","compact catalog preserves critical schema");

  const streamed=await responses({input:"COMPAT_SINGLE",stream:true,session:"compat-stream",tools:[echoTool],toolChoice:"required"}),events=sseEvents(streamed.text);assert(events.some(x=>x.type==="response.function_call_arguments.delta")&&events.some(x=>x.type==="response.function_call_arguments.done"&&/^call_/.test(x.call_id))&&events.some(x=>x.type==="response.completed")&&!streamed.text.includes("choices")&&!streamed.text.includes("[DONE]"),"native Responses SSE synthesized without Chat choices");
  const chatCall=await chat({messages:[{role:"user",content:"COMPAT_SINGLE"}],session:"compat-chat",tools:[{type:"function",function:{name:"echo_test",description:echoTool.description,parameters:echoTool.parameters}}],toolChoice:"required"});assert(chatCall.data.choices?.[0]?.message?.tool_calls?.[0]?.function?.name==="echo_test","agent Chat compatibility emits native tool_calls");
  const chatStream=await chat({messages:[{role:"user",content:"COMPAT_SINGLE"}],stream:true,session:"compat-chat-stream",tools:[{type:"function",function:{name:"echo_test",parameters:echoTool.parameters}}],toolChoice:"required"});assert(chatStream.text.includes('"tool_calls"')&&chatStream.text.includes("data: [DONE]")&&!chatStream.text.includes('"type":"tool_call"'),"agent Chat SSE emits native tool_calls and DONE");

  const named=await responses({input:"COMPAT_SINGLE",session:"compat-named",tools:[echoTool],toolChoice:{type:"function",name:"echo_test"}});assert(callOf(named.data)?.name==="echo_test","named function tool_choice honored locally");
  const searchTool={type:"function",name:"search_tool",description:"Search",parameters:{type:"object",properties:{query:{type:"string"}},required:["query"],additionalProperties:false}},second=await responses({input:"COMPAT_SECOND_TOOL",session:"compat-multi",tools:[echoTool,searchTool],toolChoice:"required"});assert(callOf(second.data)?.name==="search_tool","multiple-tool catalog selects and validates non-first tool");

  const actionCases=[
    ["download","COMPAT_ACTION_DOWNLOAD 请帮我下载这个文件","bash"],
    ["install","COMPAT_ACTION_INSTALL 请帮我安装这个安全依赖","bash"],
    ["edit","COMPAT_ACTION_EDIT 请修改这段代码","edit_file"],
    ["test","COMPAT_ACTION_TEST 请运行测试并验证结果","run_tests"]
  ];
  for(const [intent,input,tool] of actionCases){await reset();const action=await responses({input,session:`action-${intent}`,tools:actionTools,toolChoice:"auto"}),s=await stats(),admin=await api("/admin/status");assert(action.r.ok&&callOf(action.data)?.name===tool,`${intent} final-answer miss recovers to ${tool}`);assert(s.compatRequests===2&&s.toolMissContractChars>0&&s.toolMissContractChars<s.initialContractChars,`${intent} uses exactly one smaller tool-miss recovery request`);assert(admin.compatibility.last_request.client_tool_count===26&&admin.compatibility.last_request.candidate_tool_count<=12&&admin.compatibility.last_request.tool_miss_recoveries===1&&admin.compatibility.last_request.action_intents.includes(intent),`${intent} intent and bounded candidate metrics recorded: ${JSON.stringify(admin.compatibility.last_request)}`);}
  await reset();const missAlways=await responses({input:"COMPAT_ACTION_MISS_ALWAYS 请帮我下载文件",session:"action-miss-once",tools:actionTools,toolChoice:"auto"}),missAlwaysStats=await stats(),missAlwaysAdmin=await api("/admin/status");assert(missAlways.r.ok&&textOf(missAlways.data)==="仍然没有调用工具。"&&missAlwaysStats.compatRequests===2&&missAlwaysAdmin.compatibility.last_request.tool_miss_recoveries===1,"tool-miss recovery is attempted at most once even when the second decision is final_answer");
  await reset();const noMatch=await responses({input:"COMPAT_ACTION_DOWNLOAD 请帮我下载文件",session:"action-no-match",tools:[echoTool],toolChoice:"auto"}),noMatchStats=await stats(),noMatchAdmin=await api("/admin/status");assert(noMatch.r.ok&&textOf(noMatch.data)==="你可以自己下载。"&&noMatchStats.compatRequests===1&&noMatchAdmin.compatibility.last_request.tool_miss_recoveries===0,"action request without a matching executor does not trigger a futile recovery");
  await reset();const qa=await responses({input:"COMPAT_ACTION_QA 如何下载文件？只解释步骤，不要执行",session:"action-qa",tools:actionTools,toolChoice:"auto"}),qaStats=await stats(),qaAdmin=await api("/admin/status");assert(qa.r.ok&&textOf(qa.data)==="这是普通说明回答。"&&qaStats.compatRequests===1&&qaAdmin.compatibility.last_request.tool_miss_recoveries===0,"ordinary informational question does not spuriously call tools or trigger recovery");

  for(const target of ["front_catalog_tool","middle_catalog_tool","end_catalog_tool"]){await reset();const selected=await responses({input:`Use the exact tool. COMPAT_SELECT_TOOL:${target}`,session:`large-${target}`,tools:largeTools,toolChoice:"required"}),s=await stats(),admin=await api("/admin/status");assert(selected.r.ok&&callOf(selected.data)?.name===target,`55-tool Mock catalog selects ${target}`);assert(s.lastCompat.catalog.length<=12&&s.lastCompat.catalog.some(x=>x.name===target),`55-tool upstream catalog is compact and includes ${target}`);assert(admin.compatibility.last_request.client_tool_count===55&&admin.compatibility.last_request.candidate_tool_count<=12&&admin.compatibility.last_request.contract_tokens_estimate<1800,"Admin records 55-to-8 candidate and compact token metrics");}

  for(const marker of ["COMPAT_INVALID_ONCE","COMPAT_UNKNOWN_ONCE","COMPAT_MISSING_REQUIRED_ONCE","COMPAT_EXTRA_ARG_ONCE","COMPAT_WRONG_TYPE_ONCE","COMPAT_SCHEMA_ONCE","COMPAT_ROOT_ONCE","COMPAT_TYPE_ONCE","COMPAT_FINAL_INVALID_ONCE","COMPAT_EMPTY_ONCE"]){await reset();const repaired=await responses({input:marker,session:`repair-${marker}`,tools:[echoTool],toolChoice:"required"}),s=await stats();assert(repaired.r.ok&&callOf(repaired.data)?.name==="echo_test"&&s.compatRequests===2,`${marker} safely repaired exactly once (status=${repaired.r.status}, requests=${s.compatRequests}, call=${callOf(repaired.data)?.name??"none"}, error=${repaired.data?.error?.message??"none"})`);assert(s.repairContractChars>0&&s.repairContractChars<s.initialContractChars,"repair uses a smaller corrective contract");}
  await reset();const invalid=await responses({input:"COMPAT_INVALID_ALWAYS",session:"compat-invalid-max",tools:[echoTool],toolChoice:"required"}),invalidStats=await stats();assert(invalid.r.status===502&&invalidStats.compatRequests===2&&!invalid.text.includes("not json"),"invalid decision stops after maximum retry without leaking raw output");
  const duplicateInvalid=await responses({input:"COMPAT_INVALID_ALWAYS",session:"compat-invalid-max",tools:[echoTool],toolChoice:"required"}),duplicateStats=await stats();assert(duplicateInvalid.r.status===502&&duplicateInvalid.data?.error?.code==="compat_retry_suppressed"&&duplicateStats.compatRequests===2,"short-window identical client retry is suppressed without another upstream request");
  const unavailable=await responses({input:"COMPAT_SINGLE",session:"compat-unavailable",tools:[echoTool],toolChoice:{type:"function",name:"unknown"}});assert(unavailable.r.status===400,"unknown named tool rejected before upstream");
  const metricsBeforeRestart=await api("/admin/status"),reason=metricsBeforeRestart.compatibility.invalid_by_reason;for(const name of ["json_parse_error","invalid_root_shape","unknown_tool","missing_required_argument","additional_argument","argument_type_error","schema_validation_error","invalid_decision_type","final_answer_invalid","other"])assert(reason[name]>0,`Admin classifies ${name}`);assert(metricsBeforeRestart.compatibility.tool_calls>0&&metricsBeforeRestart.compatibility.invalid_decisions>0&&metricsBeforeRestart.compatibility.protocol_retries>0&&metricsBeforeRestart.compatibility.retry_suppressed>0,"Admin exposes safe compat counters and retry suppression");

  const loopInput=[{role:"user",content:"COMPAT_LOOP"}],first=(await responses({input:loopInput,session:"compat-loop",tools:loopTools,toolChoice:"required"})).data,one=callOf(first);assert(one?.name==="first_tool","loop first tool");
  const secondLoop=(await responses({input:[...loopInput,...first.output,{type:"function_call_output",call_id:one.call_id,output:"first-result"}],session:"compat-loop",tools:loopTools,toolChoice:"required"})).data,two=callOf(secondLoop);assert(two?.name==="second_tool"&&two.call_id!==one.call_id,"loop second tool and unique call_id");
  const finalLoop=(await responses({input:[...loopInput,...first.output,{type:"function_call_output",call_id:one.call_id,output:"first-result"},...secondLoop.output,{type:"function_call_output",call_id:two.call_id,output:"second-result"}],session:"compat-loop",tools:loopTools,toolChoice:"auto"})).data;assert(textOf(finalLoop)==="YUNA_COMPAT_LOOP_DONE","multi-round tool-result loop reaches final answer");

  const devInput=[{role:"user",content:"COMPAT_DEV_LOOP read then edit then test"}],devRead=(await responses({input:devInput,session:"compat-dev-loop",tools:devTools,toolChoice:"required"})).data,readCall=callOf(devRead);assert(readCall?.name==="read_file","development loop starts with read");const devEdit=(await responses({input:[...devInput,...devRead.output,{type:"function_call_output",call_id:readCall.call_id,output:"safe temporary content"}],session:"compat-dev-loop",tools:devTools,toolChoice:"required"})).data,editCall=callOf(devEdit);assert(editCall?.name==="edit_file","development loop continues with edit");const devTest=(await responses({input:[...devInput,...devRead.output,{type:"function_call_output",call_id:readCall.call_id,output:"safe temporary content"},...devEdit.output,{type:"function_call_output",call_id:editCall.call_id,output:"edited"}],session:"compat-dev-loop",tools:devTools,toolChoice:"required"})).data,testCall=callOf(devTest);assert(testCall?.name==="run_test","development loop continues with test");const devFinal=(await responses({input:[...devInput,...devRead.output,{type:"function_call_output",call_id:readCall.call_id,output:"safe temporary content"},...devEdit.output,{type:"function_call_output",call_id:editCall.call_id,output:"edited"},...devTest.output,{type:"function_call_output",call_id:testCall.call_id,output:"PASS"}],session:"compat-dev-loop",tools:devTools,toolChoice:"auto"})).data;assert(textOf(devFinal)==="星铃｜DEV_LOOP_DONE","read-edit-test loop reaches Persona-styled final answer");

  await responses({input:"COMPAT_POLLUTION_CASE",session:"compat-pollution",tools:[echoTool],toolChoice:"required"}).then(async firstPollution=>responses({input:[{role:"user",content:"COMPAT_POLLUTION_CASE"},...firstPollution.data.output,{type:"function_call_output",call_id:callOf(firstPollution.data).call_id,output:"terminal output\ngit diff @@\nauth.ts:317 SECRET_TOOL_OUTPUT_XYZ"}],session:"compat-pollution",tools:[],toolChoice:"none"}));
  await waitFor(async()=>(await api("/admin/status")).workers.summary_running===0,"pollution summary");const leakDb=new DatabaseSync(dbPath,{readOnly:true}),leaks=leakDb.prepare("SELECT COUNT(*) c FROM memories WHERE content LIKE '%SECRET_TOOL_OUTPUT_XYZ%' OR content LIKE '%git diff%' OR content LIKE '%auth.ts:317%' OR content LIKE '%tool_call%'").get().c;leakDb.close();assert(leaks===0,"compat JSON, arguments, tool output and code do not enter Shared Memory");

  await responses({input:"PROJECT_A_SECRET",headers:{"x-cwd":"/Users/example-4/a/SameName"}});await responses({input:"PROJECT_B_SECRET",headers:{"x-cwd":"/Users/example-4/b/SameName"}});const projects=(await api("/admin/sessions?source=opencode&limit=100")).data.filter(x=>x.external_key.startsWith("project-samename-"));assert(projects.length===2&&new Set(projects.map(x=>x.external_key)).size===2,"two same-name projects remain isolated");
  const projectDb=new DatabaseSync(dbPath,{readOnly:true});for(const project of projects){const texts=projectDb.prepare("SELECT content_text FROM messages WHERE session_id=?").all(project.id).map(x=>x.content_text??"").join("\n");assert(!(texts.includes("PROJECT_A_SECRET")&&texts.includes("PROJECT_B_SECRET")),"raw project messages never cross Sessions");}projectDb.close();
  await responses({input:"HARNESS_STABLE_ONE",headers:{"x-companion-source":"harness","x-session-id":"harness-project-a"}});await responses({input:"HARNESS_STABLE_TWO",headers:{"x-companion-source":"harness","x-session-id":"harness-project-a"}});await responses({input:"HARNESS_OTHER_PROJECT",headers:{"x-companion-source":"harness","x-session-id":"harness-project-b"}});const harnessSessions=(await api("/admin/sessions?source=harness&limit=100")).data.filter(x=>x.external_key.startsWith("project-harness-project-"));assert(harnessSessions.length===2&&new Set(harnessSessions.map(x=>x.external_key)).size===2,"Harness x-session-id is stable within one project task and isolated across projects");

  await reset();const ac=new AbortController(),pending=fetch(`http://127.0.0.1:${corePort}/v1/responses`,{method:"POST",signal:ac.signal,headers:{authorization:`Bearer ${key}`,"content-type":"application/json","x-companion-source":"opencode","x-companion-session":"compat-cancel"},body:JSON.stringify({model:"yuna-agent",input:"COMPAT_CANCEL",tools:[echoTool],tool_choice:"required"})});await sleep(80);ac.abort();try{await pending;}catch{}await sleep(180);assert((await stats()).aborted>=1,"compat client cancel aborts upstream");
  assert((await responses({input:"TIMEOUT",session:"compat-timeout"})).r.status===504,"compat timeout wrapped");assert([502,503].includes((await responses({input:"CONNECTION_RESET",session:"compat-reset"})).r.status),"compat reset is wrapped or stopped by the circuit breaker");for(const code of [429,500]){const fault=await responses({input:`FAULT_${code}`,session:`compat-fault-${code}`});assert([code,502,503].includes(fault.r.status),`compat transient provider ${code} is retried or stopped by the circuit breaker`);}await sleep(1100);assert((await responses({input:"CIRCUIT_RECOVERY_PROBE",session:"compat-circuit-probe"})).r.ok,"compat circuit half-open probe closes after a successful request");

  await reset();await Promise.all([responses({input:"SLOW_A",session:"compat-parallel-a"}),responses({input:"SLOW_B",session:"compat-parallel-b"})]);assert((await stats()).maxMainActive>=2,"different compat Sessions run in parallel");await reset();await Promise.all([responses({input:"SLOW_ONE",session:"compat-serial"}),responses({input:"SLOW_TWO",session:"compat-serial"})]);assert((await stats()).maxMainActive===1,"same compat Session is serialized");

  const restartFirst=(await responses({input:"COMPAT_SINGLE",session:"compat-restart",tools:[echoTool],toolChoice:"required"})).data,restartCall=callOf(restartFirst);const before=await api("/admin/status");await stop(core);core=start(path.join(root,"src/server.js"),{...env,PERSONA_SYNC_ON_START:"false"});await wait(`http://127.0.0.1:${corePort}/health`);const after=await api("/admin/status");assert(after.sessions===before.sessions&&after.messages===before.messages&&after.memories===before.memories,"compat persistence survives restart");const afterResult=await responses({input:[{type:"function_call_output",call_id:restartCall.call_id,output:"after-restart-result"}],session:"compat-restart",tools:[],toolChoice:"none"});assert(textOf(afterResult.data)==="YUNA_COMPAT_FINAL", "tool result accepted after restart");const mapped=(await stats()).lastCompat;assert(mapped.toolResultContext.includes("tool: echo_test")&&mapped.toolResultContext.includes(restartCall.call_id),"persisted call_id maps to tool name after restart");

  const usage=await api("/admin/usage?group_by=kind&kind=agent");assert(usage.data.some(x=>x.bucket==="agent"&&x.prompt_tokens>0&&x.completion_tokens>0&&x.cached_tokens>0),"compat usage recorded as agent including cached tokens");
  const kelivo=await chat({messages:[{role:"user",content:"普通聊天"}],session:"kelivo-chat",model:"yuna-chat",source:"kelivo"});assert(kelivo.r.ok&&kelivo.data.choices[0].message.content==="MOCK_OK", "Kelivo yuna-chat stays entirely outside compat");const finalStats=await stats();assert(finalStats.lastCompat.toolResultContext.includes("after-restart-result"),"compat result context retained for final verification");
  console.log("\nPASS Companion Core v0.2.6.0 action intents and one-time tool-miss recovery: protocol, validation, Persona/Memory, loops, isolation, faults, cancel, concurrency, usage, restart, and Kelivo regression");
}finally{for(const p of [...children].reverse())await stop(p);await sleep(80);fs.rmSync(tmp,{recursive:true,force:true});}
