import fs from "node:fs";
import path from "node:path";
import { config } from "./config.js";
import { uuid } from "./utils.js";
import { CompanionTimeService } from "./time-service.js";

const TOKEN_FIELDS=["inputTokens","cachedInputTokens","reasoningTokens","outputTokens"];
const emptyMetric=()=>({requests:0,inputTokens:{sum:0,known:0},cachedInputTokens:{sum:0,known:0},reasoningTokens:{sum:0,known:0},outputTokens:{sum:0,known:0},costUsd:{sum:0,known:0},unknownUsage:0,unpriced:0});
const initialIndex=()=>({version:2,records:0,seenKeys:[],today:{},months:{},providers:{},models:{},features:{},recent:[]});
function atomic(file,value){fs.mkdirSync(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.${uuid()}.tmp`;fs.writeFileSync(tmp,JSON.stringify(value,null,2),{mode:0o600});fs.renameSync(tmp,file);try{fs.chmodSync(file,0o600);}catch{}}
function nullableInteger(value){if(value===null||value===undefined)return null;const number=Number(value);return Number.isInteger(number)&&number>=0?number:null;}
function addMetric(metric,record){metric.requests+=record.requestCount;for(const field of TOKEN_FIELDS){if(record[field]!==null){metric[field].sum+=record[field];metric[field].known+=record.requestCount;}}if(record.costUsd!==null){metric.costUsd.sum+=record.costUsd;metric.costUsd.known+=record.requestCount;}if(record.costStatus==="unknown_usage"||record.costStatus==="partial")metric.unknownUsage+=record.requestCount;if(record.costStatus==="unpriced")metric.unpriced+=record.requestCount;}
function metricOutput(metric){const out={requests:metric.requests,unknownUsage:metric.unknownUsage,unpriced:metric.unpriced};for(const field of TOKEN_FIELDS)out[field]=metric[field].known?metric[field].sum:null;out.costUsd=metric.costUsd.known?Number(metric.costUsd.sum.toFixed(9)):null;return out;}
function bucket(map,key,record){if(!map[key])map[key]=emptyMetric();addMetric(map[key],record);}
function parseProviderModel(raw){const text=String(raw??"");const index=text.indexOf(":");return index>0?{provider:text.slice(0,index),model:text.slice(index+1)}:{provider:"unknown",model:text||"unknown"};}
function usageFields(usage){return {inputTokens:nullableInteger(usage?.prompt_tokens??usage?.input_tokens),cachedInputTokens:nullableInteger(usage?.cached_tokens??usage?.prompt_tokens_details?.cached_tokens??usage?.input_tokens_details?.cached_tokens),reasoningTokens:nullableInteger(usage?.reasoning_tokens??usage?.completion_tokens_details?.reasoning_tokens??usage?.output_tokens_details?.reasoning_tokens),outputTokens:nullableInteger(usage?.completion_tokens??usage?.output_tokens)};}

export class InvocationLedger{
  constructor({ledgerPath=config.invocationLedgerPath,summaryPath=config.invocationSummaryPath,pricesPath=config.pricingRevisionsPath,now=()=>new Date(),timeService=null}={}){this.ledgerPath=ledgerPath;this.summaryPath=summaryPath;this.pricesPath=pricesPath;this.now=now;this.time=timeService??new CompanionTimeService({clock:now});this.prices=this.loadPrices();this.index=this.loadIndex();}
  loadPrices(){try{const value=JSON.parse(fs.readFileSync(this.pricesPath,"utf8"));return value?.version===1&&Array.isArray(value.revisions)?value:{version:1,revisions:[]};}catch{return {version:1,revisions:[]};}}
  loadIndex(){try{const value=JSON.parse(fs.readFileSync(this.summaryPath,"utf8"));if(value?.version===2)return value;}catch{}return this.rebuild();}
  rebuild(){const index=initialIndex();if(!fs.existsSync(this.ledgerPath))return index;const raw=fs.readFileSync(this.ledgerPath,"utf8"),lines=raw.split("\n");let good=[];for(let i=0;i<lines.length;i++){if(!lines[i])continue;try{const record=JSON.parse(lines[i]);good.push(lines[i]);this.apply(index,record);}catch{const backup=`${this.ledgerPath}.corrupt-${Date.now()}`;fs.copyFileSync(this.ledgerPath,backup);fs.writeFileSync(this.ledgerPath,good.length?`${good.join("\n")}\n`:"",{mode:0o600});break;}}atomic(this.summaryPath,index);return index;}
  activePrice(provider,model,timestamp){return this.prices.revisions.filter(x=>x.provider===provider&&x.model===model&&new Date(x.effectiveFrom)<=new Date(timestamp)).sort((a,b)=>b.effectiveFrom.localeCompare(a.effectiveFrom))[0]??null;}
  calculateCost(fields,revision){
    if(fields.inputTokens===null&&fields.outputTokens===null)return {costUsd:null,costStatus:"unknown_usage",priceRevisionId:null};
    if(!revision)return {costUsd:null,costStatus:"unpriced",priceRevisionId:null};
    if(fields.inputTokens===null||fields.outputTokens===null)return {costUsd:null,costStatus:"partial",priceRevisionId:revision.id};
    let input=fields.inputTokens,output=fields.outputTokens,cost=0;
    if(revision.cachedInputPerMillion!==null){if(fields.cachedInputTokens===null)return {costUsd:null,costStatus:"partial",priceRevisionId:revision.id};input=Math.max(0,input-fields.cachedInputTokens);cost+=fields.cachedInputTokens*revision.cachedInputPerMillion/1e6;}
    if(revision.reasoningPerMillion!==null){if(fields.reasoningTokens===null)return {costUsd:null,costStatus:"partial",priceRevisionId:revision.id};output=Math.max(0,output-fields.reasoningTokens);cost+=fields.reasoningTokens*revision.reasoningPerMillion/1e6;}
    cost+=input*revision.inputPerMillion/1e6+output*revision.outputPerMillion/1e6;return {costUsd:Number(cost.toFixed(12)),costStatus:"priced",priceRevisionId:revision.id};
  }
  apply(index,record){index.records++;if(record.requestKey){index.seenKeys.push(record.requestKey);index.seenKeys=index.seenKeys.slice(-4096);}const day=this.time.localDate(record.timestamp),month=this.time.localMonth(record.timestamp);bucket(index.today,day,record);bucket(index.months,month,record);bucket(index.providers,record.provider,record);bucket(index.models,`${record.provider}:${record.model}`,record);bucket(index.features,record.feature,record);index.recent.unshift(record);index.recent=index.recent.slice(0,50);}
  append(input){
    const timestamp=new Date(input.timestamp??this.now()).toISOString(),requestKey=input.requestKey?String(input.requestKey):null;if(requestKey&&this.index.seenKeys.includes(requestKey))return null;
    const parsed=parseProviderModel(input.upstreamModel),fields=input.usage?usageFields(input.usage):{inputTokens:nullableInteger(input.inputTokens),cachedInputTokens:nullableInteger(input.cachedInputTokens),reasoningTokens:nullableInteger(input.reasoningTokens),outputTokens:nullableInteger(input.outputTokens)};
    const provider=String(input.provider??parsed.provider),model=String(input.model??parsed.model),revision=this.activePrice(provider,model,timestamp),cost=this.calculateCost(fields,revision);
    const durationMs=Number(input.durationMs),record={id:String(input.id??uuid()),requestKey,timestamp,provider,model,publicModel:String(input.publicModel??""),feature:String(input.feature??input.kind??"unknown"),source:String(input.source??""),session:input.sessionId??null,requestCount:Math.max(1,Number(input.requestCount)||1),durationMs:Number.isFinite(durationMs)&&durationMs>=0?Math.round(durationMs):null,success:typeof input.success==="boolean"?input.success:null,...fields,usageSource:String(input.usageSource??"provider"),...cost};
    fs.mkdirSync(path.dirname(this.ledgerPath),{recursive:true});fs.appendFileSync(this.ledgerPath,`${JSON.stringify(record)}\n`,{mode:0o600});this.apply(this.index,{...record,requestKey});atomic(this.summaryPath,this.index);return record;
  }
  addPrice(input){const numberOrNull=value=>value===null||value===undefined||value===""?null:Number(value);const revision={id:uuid(),provider:String(input.provider??"").trim(),model:String(input.model??"").trim(),inputPerMillion:numberOrNull(input.inputPerMillion),cachedInputPerMillion:numberOrNull(input.cachedInputPerMillion),outputPerMillion:numberOrNull(input.outputPerMillion),reasoningPerMillion:numberOrNull(input.reasoningPerMillion),effectiveFrom:new Date(input.effectiveFrom??this.now()).toISOString(),createdAt:this.now().toISOString()};if(!revision.provider||!revision.model||revision.inputPerMillion===null||revision.outputPerMillion===null||[revision.inputPerMillion,revision.outputPerMillion,revision.cachedInputPerMillion,revision.reasoningPerMillion].filter(x=>x!==null).some(x=>!Number.isFinite(x)||x<0))throw new Error("invalid price revision");this.prices.revisions.push(revision);atomic(this.pricesPath,this.prices);return revision;}
  importLegacyRows(rows){let count=0;for(const row of rows??[]){const appended=this.append({timestamp:row.created_at,requestKey:`legacy-sql:${row.id}`,sessionId:row.session_id,source:row.source,publicModel:row.public_model,upstreamModel:row.upstream_model,feature:row.kind,usage:{prompt_tokens:row.prompt_tokens,completion_tokens:row.completion_tokens,cached_tokens:row.cached_tokens,total_tokens:row.total_tokens},usageSource:"legacy_sql"});if(appended)count++;}return count;}
  snapshot(){const current=this.now(),now=current.toISOString(),day=this.time.localDate(current),month=this.time.localMonth(current);return {generatedAt:now,timeZone:this.time.timeZone,localDate:day,localMonth:month,todayUtcRange:this.time.localDayBoundsToUTC(day),monthUtcRange:this.time.localMonthBoundsToUTC(month),ledgerFormat:"jsonl-v1",summaryFormat:"incremental-sidecar-v2",today:metricOutput(this.index.today[day]??emptyMetric()),month:metricOutput(this.index.months[month]??emptyMetric()),providers:Object.entries(this.index.providers).map(([key,value])=>({key,...metricOutput(value)})).sort((a,b)=>b.requests-a.requests),models:Object.entries(this.index.models).map(([key,value])=>({key,...metricOutput(value)})).sort((a,b)=>b.requests-a.requests),features:Object.entries(this.index.features).map(([key,value])=>({key,...metricOutput(value)})).sort((a,b)=>b.requests-a.requests),recent:this.index.recent,prices:[...this.prices.revisions].sort((a,b)=>b.effectiveFrom.localeCompare(a.effectiveFrom))};}
}

export const invocationLedger=new InvocationLedger();
export const invocationUsageFields=usageFields;
